### PR TITLE
Fix text positioning to avoid cropping

### PR DESCRIPTION
**Pull request by nicohein**
Hi @adamchainz,

I just ran a quick local test and this little change seems to fix the issue https://github.com/adamchainz/treepoem/issues/495. I am not sure if there may be any side effects even though I could not spot any. (If the number is increased to a greater value the final plot seems to remain stable.)

I would appreciate if you could take a look.

Best
Nico

### CODE REVIEW

**Comment by adamchainz** [comment]
I’ve got to admit I have not much memory of the postscript coordinate system here. 11 feels a bit arbitrary. What are the potential problems here?

**Comment by nicohein** [comment]
How I understand this, is that with the ghostscript call we are getting the bounding box for the bbox device which only returns positive values. This means that everything plotted in the coordinate system with one coordinate in a negative position is cropped.
Now, this bwipp change in [ean13.ps line 59](https://github.com/bwipp/postscriptbarcode/blame/master/src/ean13.ps#L59C5-L59C25) changed the textxoffset for the first number from -10 to -11. In your code you move the whole symbol returned by bwipp to position 10 10. i.e. shift the coordinate system reference. This worked until now because 10 was the greatest negative position that was plotted to. 

If we would increase the value to 100, we would gut get the first bbox value as 89 (100-11) for EAN13. 
A quick test with `100 100 moveto` and `scale=1` indeed reveals:

```
%%BoundingBox: 89 95 195 122
%%HiResBoundingBox: 89.333997 95.723997 194.939994 121.607996
```

The final result remains as expected.

**Comment by terryburton** [comment]
GS (specifically the `bbox` device) has a `PageOffset` option that can be used to shift the entire coordinate system without consuming extra memory. Via GS arguments: `-sDEVICE=bbox -dPAGEOFFSET=$PAGE_OFFSET`

If you wish to use this approach, then for processing TreePoem's "bbox template" make sure `PageOffset` is sufficient to ensure that the symbol is always shifted into the first quadrant, e.g. 3000.

Then for the "EPS template", do not set a `PageOffset`, but rather use what you've learned from the bounding box returned when processing the bbox template to first "moveto" the position in the page that ensures that the resulting image is aligned with the coordinate system's origin. Then you can generate a well-formed EPS with a bounding box of the form "0 0 X Y".

**Comment by terryburton** [comment]
> GS (specifically the `bbox` device) has a `PageOffset` option that can be used to shift the entire coordinate system without consuming extra memory. Via GS arguments: `-sDEVICE=bbox -c "<</PageOffset [$PAGE_OFFSET $PAGE_OFFSET]>> setpagedevice"`

I wrote this up here:

https://github.com/bwipp/postscriptbarcode/wiki/Developing-a-Frontend-to-BWIPP#generating-cropped-images-via-eps

**Comment by adamchainz** [comment]
Thank you Terry. Looks like Treepoem needs a few adjustments to follow all of your latest docs. Working on that.

**Comment by adamchainz** [comment]
I've added a test for the fixed text positioning on EAN13. I'm gonna merge this PR and then iterate on using the latest guidance from BWIPP.

**Pull request merged**
